Parameters:
  SnsName: 
    Type: string
    Description: Value Name Topic SNS

Resources:    
  OpsEventRule: 
    Type: AWS::Events::Rule
    Properties: 
      Description: "EventRule"
      EventPattern: 
        source: 
         - "aws.config"
        detail-type: 
         - "Config Rules Compliance Change"
        detail:
         messageType:
            - "ComplianceChangeNotification"
        configRuleName: 
         - "iam-user-mfa-enabled"
        resourceType: 
         - "AWS::IAM::User"
        newEvaluationResult:
         complianceType": 
           - "NON_COMPLIANT"
      State: "ENABLED"
      Targets: 
        - 
          Arn: 
            Ref: SnsName
          Id: "OpsTopic"
  EventTopicPolicy:
    Type: 'AWS::SNS::TopicPolicy'
    Properties:
      PolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service: events.amazonaws.com
            Action: 'sns:Publish'
            Resource: '*'
      Topics:
        Ref: SnsName
  InputTransformer:
    InputPathsMap:
      "instance" : "$.detail.instance-id"
      "state" : "$.detail.state"
      "Arn" : "$.detail.Resource_ARN"
      "awsAccountId" : "$.detail.awsAccountId"
      "awsRegion" : "$.detail.awsRegion"
      "compliance" : "$.detail.newEvaluationResult.complianceType"
      "resourceId" : "$.detail.resourceId"
      "resourceType" : "$.detail.resourceType"
      "rule" : "$.detail.configRuleName"
      "time" : "$.detail.newEvaluationResult.resultRecordedTime"
    InputTemplate: |
      {
        "On <time> AWS Config rule <rule> evaluated the <resourceType> with Id <resourceId> in the account <awsAccountId> region <awsRegion> as <compliance> ARN<Arn> For more details open the AWS Config console at https://console.aws.amazon.com/config/home?region=<awsRegion>#/timeline/<resourceType>/<resourceId>/configuration"
      }

